Ref #48727 fixed the "Division by zero" error.
DOM-Digital-Online-Media/spreadspace_cancel pull request #7
Opened 2023-09-07 12:18 UTC by ShamryloMykola

2023-09-08 10:49 UTC, andrew-sereda requested changes
I would also suggest to throw an exception at start of this method if either $w or $h equals 0.
Both of those variable used in division and if it's 0 will be an error. We should throw an exception saying that this value cannot be equal to 0,also would be good to add this to phpdoc to make sure devs in future won't put 0 there.

2023-09-08 10:49 UTC, andrew-sereda commented on src/Plugin/rest/resource/ContractCancelResource.php
> +    $lines = ceil($text_width / ($w > 0 ? $w : $text_width));
```suggestion
    $lines = $text_width ? ceil($text_width / $w) : 1;
```

2023-09-11 16:05 UTC, ShamryloMykola commented on src/Plugin/rest/resource/ContractCancelResource.php
> +    $lines = ceil($text_width / ($w > 0 ? $w : $text_width));
Done.

2023-09-12 09:59 UTC, andrew-sereda approved these changes

2023-09-12 09:59 UTC, merged